# Generated by Django 3.2.6 on 2021-12-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.songcategory'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
