# Generated by Django 3.2.6 on 2021-12-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20211221_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music.songcategory'),
        ),
    ]
