# Generated by Django 3.2.6 on 2021-12-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.userdetails'),
            preserve_default=False,
        ),
    ]
