# Generated by Django 3.2.6 on 2021-12-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='uid',
            new_name='userid',
        ),
    ]
