# Generated by Django 3.2.6 on 2021-12-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rename_uid_song_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcategory',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.userdetails'),
        ),
    ]
