# Generated by Django 3.2.6 on 2021-12-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_songcategory_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songcategory',
            old_name='uid',
            new_name='userid',
        ),
        migrations.AlterField(
            model_name='songcategory',
            name='categoryname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
