# Generated by Django 3.2.6 on 2022-01-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_album_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='dislikes',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
